//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventTable
    {
        [Required(ErrorMessage = "{0} Required Field!")]
        public int EventID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string EventTitle { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime EventDate { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Location { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public int UserID { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
