//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExamTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamTable()
        {
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
        }
        [Required(ErrorMessage = "{0} Required Field!")]
        public int ExamID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public int UserID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Title { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "{0} Required Field!")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime StartDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "{0} Required Field!")]
        public System.DateTime EndDate { get; set; }
        [DataType(DataType.MultilineText)]
        public string Descrption { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
    }
}
