//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExpensesTable
    {
        [Required(ErrorMessage = "{0} Required Field!")]
        public int ExpensesID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public int ExpensesTypeID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ExpensesDate { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]

        [DisplayFormat(DataFormatString = "{0:#,##0 VND}", ApplyFormatInEditMode = true)]
        public double Amount { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Reason { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public int UserID { get; set; }

        public virtual ExpenseTypeTable ExpenseTypeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
