//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
  
    ViewBag.Title = "Index";


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
  
    int usertypeid = Convert.ToInt32(Convert.ToString(Session["UserTypeID"]));
    if (usertypeid == 1)
    {
        

#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
       __o = Html.ActionLink("Promote Student", "Create", null, new { @class = "btn btn-success" });


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
            
    }



#line default
#line hidden

#line 6 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                                  __o = usertypeid == 1 ? "All " : "" ;


#line default
#line hidden

#line 7 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                    foreach (var item in Model)
                    {
                        

#line default
#line hidden

#line 8 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.StudentPromotID);


#line default
#line hidden

#line 9 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.StudentTable.Name);


#line default
#line hidden

#line 10 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.PromoteDate);


#line default
#line hidden

#line 11 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.AnnualFee);


#line default
#line hidden

#line 12 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.IsActive);


#line default
#line hidden

#line 13 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.IsSubmit);


#line default
#line hidden

#line 14 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.ClassTable.Name);


#line default
#line hidden

#line 15 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                           __o = Html.DisplayFor(modelItem => item.SectionTable.SectionName);


#line default
#line hidden

#line 16 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                  
                                    if (usertypeid == 1)
                                    {
                                        

#line default
#line hidden

#line 17 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                   __o = Html.ActionLink("Edit", "Edit", new { id = item.StudentPromotID }, new { @class = "btn btn-primary" });


#line default
#line hidden

#line 18 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                                                                                                                               
                                        

#line default
#line hidden

#line 19 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                   __o = Html.ActionLink("Details", "Details", new { id = item.StudentPromotID }, new { @class = " btn btn-info" });


#line default
#line hidden

#line 20 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                                                                                                                                   
                                        

#line default
#line hidden

#line 21 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                   __o = Html.ActionLink("Delete", "Delete", new { id = item.StudentPromotID }, new { @class = "btn btn-danger" });


#line default
#line hidden

#line 22 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                                                                                                                                  
                                    }
                                    else
                                    {
                                        

#line default
#line hidden

#line 23 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                   __o = Html.ActionLink("Details", "Details", new { id = item.StudentPromotID }, new { @class = " btn btn-info" });


#line default
#line hidden

#line 24 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                                                                                                                                                   
                                    }
                                

#line default
#line hidden

#line 25 "C:\Users\Admin\AppData\Local\Temp\EA9EE3992EDDC5527FFB27D40AE48D01E4CB\2\EzSchool\EzSchool\Views\StudentPromotTables\Index.cshtml"
                             
                    }

#line default
#line hidden
}
}
}
